=== MoatazNoaman2001/iti-assignemnts/xml lab3/trainee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="TraineeAffairs">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Trainees">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Trainee" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        
                                        <xs:element name="Name" type="xs:string"/>
                                        <xs:element name="Age" type="xs:string"/>
                                        <xs:element name="Address">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Governorate" type="xs:string"/>
                                                    <xs:element name="Street" type="xs:string"/>
                                                    <xs:element name="ZipCode" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Phone" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                                        <xs:element name="Group">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="value" type="xs:string" use="required">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:string">
                                                                    <xs:enumeration value="1"/>
                                                                    <xs:enumeration value="2"/>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Results">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="CourseResult" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="CourseName" type="xs:string"/>
                                                            </xs:sequence>
                                                            <xs:attribute name="Grade" use="required">
                                                                <xs:simpleType>
                                                                    <xs:restriction base="xs:string">
                                                                        <xs:enumeration value="A"/>
                                                                        <xs:enumeration value="B"/>
                                                                        <xs:enumeration value="C"/>
                                                                        <xs:enumeration value="D"/>
                                                                        <xs:enumeration value="E"/>
                                                                    </xs:restriction>
                                                                </xs:simpleType>
                                                            </xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== MoatazNoaman2001/iti-assignemnts/xml lab3/trainee.xml
<?xml version="1.0" encoding="UTF-8"?>
<TraineeAffairs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="trainee.xsd">
    <Trainees>
        <Trainee>
            <Name>Ahmed Ali</Name>
            <Age>23</Age>
            <Address>
                <Governorate>Assiut</Governorate>
                <Street>El Nil Street</Street>
                <ZipCode>71111</ZipCode>
            </Address>
            <Phone>01012345678</Phone>
            <Phone>01234567890</Phone>
            <Group value="1">Group 1</Group>
            <Results>
                <CourseResult Grade="A">
                    <CourseName>XML Basics</CourseName>
                </CourseResult>
                <CourseResult Grade="A">
                    <CourseName>Web Development</CourseName>
                </CourseResult>
            </Results>
        </Trainee>
        
        <Trainee>
            <Name>Sara Mahmoud</Name>
            <Age>21</Age>
            <Address>
                <Governorate>Sohag</Governorate>
                <Street>El Huria Street</Street>
                <ZipCode>82511</ZipCode>
            </Address>
            <Phone>01198765432</Phone>
            <Group value="2">Group 2</Group>
            <Results>
                <CourseResult Grade="A">
                    <CourseName>Java Programming</CourseName>
                </CourseResult>
                <CourseResult Grade="A">
                    <CourseName>Database Design</CourseName>
                </CourseResult>
            </Results>
        </Trainee>
    </Trainees>
</TraineeAffairs>
