=== MoatazNoaman2001/iti-assignemnts/xml lab2/trainee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xsd:element name="TraineeAffairs">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Trainee" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Address">
                                <xsd:complexType>
                                    <xsd:complexContent>
                                        <xsd:restriction base="xsd:anyType">
                                            <xsd:attribute name="Governorate" type="xsd:string" use="required" />
                                            <xsd:attribute name="Street" type="xsd:string" use="required" />
                                            <xsd:attribute name="ZipCode" type="xsd:string" use="optional" />
                                        </xsd:restriction>
                                    </xsd:complexContent>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="Phone" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
                            <xsd:element name="CourseResult">
                                <xsd:complexType>
                                    <xsd:complexContent>
                                        <xsd:restriction base="xsd:anyType">
                                            <xsd:attribute name="CourseName" type="xsd:string" use="required" />
                                    <xsd:attribute name="TraineeGrade" use="required">
                                        <xsd:simpleType>
                                            <xsd:restriction base="xsd:string">
                                                <xsd:enumeration value="A" />
                                                <xsd:enumeration value="B" />
                                                <xsd:enumeration value="C" />
                                                <xsd:enumeration value="D" />
                                                <xsd:enumeration value="E" />
                                            </xsd:restriction>
                                        </xsd:simpleType>
                                    </xsd:attribute>
                                        </xsd:restriction>
                                    </xsd:complexContent>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="Name" type="xsd:string" use="required" />
                        <xsd:attribute name="Age" type="xsd:string" use="required" />
                        <xsd:attribute name="Group">
                            <xsd:simpleType>
                                <xsd:restriction base="xsd:string">
                                    <xsd:enumeration value="group1" />
                                    <xsd:enumeration value="group2" />
                                </xsd:restriction>
                            </xsd:simpleType>
                        </xsd:attribute>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== MoatazNoaman2001/iti-assignemnts/xml lab2/trainee.xml
<?xml version="1.0" encoding="UTF-8"?>
<TraineeAffairs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="trainee.xsd">
	<Trainee Name="basma" Age="23" Group="group1">
		<Address Governorate="Minia" Street="el nahda st" ZipCode="61111"/>
		<Phone>1234567</Phone>
		<Phone>0100784</Phone>
		<CourseResult CourseName="xml" TraineeGrade="B"/>
	</Trainee>
	<Trainee Group="group1" Age="22" Name="Ahmed">
		<Address Governorate="Assuit" Street="Helaly" ZipCode="71111"/>
		<CourseResult TraineeGrade="B" CourseName="C#"/>
	</Trainee>
</TraineeAffairs>
